config/routes.rb
Rails.application.routes.draw do
  resources :hidden_notes
  root to: "hidden_notes#new"

  match '/messages/api' => 'hidden_notes#create', via: :post

  # For detail s on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hidden_note.rb
class HiddenNote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/hidden_notes_controller.rb
class HiddenNotesController < ApplicationController
before_action :set_hidden_note, only: [:show, :destroy]

  # GET /hidden_notes
  # GET /hidden_notes.json
  def index
    @hidden_notes = HiddenNote.all
  end

  # GET /hidden_notes/1
  # GET /hidden_notes/1.json
  def show
   @hidden_note.destroy
   respond_to do |format|
    format.html { render :show, notice: 'This Hidden note is now successfully destroyed.'}
    format.json { head :no_content }
  end
end
  # i made dis
  def show_url
  end

  # GET /hidden_notes/new
  def new
    @hidden_note = HiddenNote.new
  end

  # POST /hidden_notes
  # POST /hidden_notes.json
  def create
    messages_url = "https://do-not-keep-that.herokuapp.com/hidden_notes"
    if request.content_type =~ /xml/
    message_hash = Hash.from_xml(request.body.read)

         params[:hidden_note] = {"your_note" => message_hash["message"]}

         @hidden_note = HiddenNote.create(hidden_note_params)

         url = '<?xml version = "1.0" encoding = "UTF-8" standalone ="yes"?>' +
               "<url>" +
                 messages_url + '/' + @hidden_note.id.to_s +
               "</url>"

         render :xml => url
       else
         respond_to do |format|
             format.json {
               params[:hidden_note] = {"your_note" => params[:message]}

               @hidden_note = HiddenNote.create(hidden_note_params)

               url = {"url" => messages_url + "/" + @hidden_note.id.to_s}

               render :json => url.to_json
             }

             format.html {
               @hidden_note = HiddenNote.create(hidden_note_params)

               render :get
             }
         end

    end

  # if request.content_type =~ /xml/
  #   params[:your_note] = Hash.from_xml(request.body.read)["message"]
  #   notes_url = "https://do-not-keep-that.herokuapp.com/hidden_notes/#{hidden_note.id}"
  #   hidden_note = HiddenNote.new(your_note: params[:your_note])
  #   render xml:
  #   '<?xml version = "1.0" encoding = "UTF-8" standalone = "yes"?>' + '<url>' +  notes_url + hidden_note.id + "/info" + '</url>'
  # elsif request.content_type =~ /json/
  #  hidden_note = HiddenNote.new(your_note: params[:your_note])
  #   notes_url = "https://do-not-keep-that.herokuapp.com/hidden_notes/#{hidden_note.id}"
  #  render json: {url: notes_url + hidden_note.id + '/info'}
  # elsif request.content_type =~ /form/
  #   @hidden_note = HiddenNote.new(hidden_note_params)
  #   respond_to do |format|
  #    if @hidden_note.save
  #       format.html { render :show_url, notice: 'Hidden note was successfully created.'}
  #       format.json { render :show_url, status: :created, location: @hidden_note }
  #    else
  #       format.html { render :new }
  #       format.json { render json: @hidden_note.errors, status: :unprocessable_entity }
  #    end
  #   end
  # end
end

  # DELETE /hidden_notes/1
  # DELETE /hidden_notes/1.json
  def destroy
    @hidden_note.destroy
    respond_to do |format|
      format.html { redirect_to hidden_notes_url, notice: 'Hidden note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hidden_note
      @hidden_note = HiddenNote.find_by(id: params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hidden_note_params
      params.require(:hidden_note).permit(:your_note)
    end
    def hidden_note_api_params
      params.permit(:your_note)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hidden_notes_helper.rb
module HiddenNotesHelper
end

app/views/hidden_notes/_form.html.erb
<%= form_with(model: hidden_note, local: true) do |form| %>
<% if hidden_note.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(hidden_note.errors.count, "error") %> prohibited this hidden_note from being saved:</h2>

  <ul>
    <% hidden_note.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= simple_format(form.label :your_note) %>
  <%= form.text_area :your_note, id: :hidden_note_your_note %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/hidden_notes/curl_post_example.html.erb
<body>
  <%= yield %>
</body>

app/views/hidden_notes/edit.html.erb
<h1>Editing Hidden Note</h1>

<%= render 'form', hidden_note: @hidden_note %>

<%= link_to 'Show', @hidden_note %> |
<%= link_to 'Back', hidden_notes_path %>

app/views/hidden_notes/index.html.erb
<h2>Hidden Notes</h2>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Your note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hidden_notes.each do |hidden_note| %>
      <tr>
        <td><%= hidden_note.your_note %></td>
        <td><%= link_to 'Show', hidden_note %></td>
        <td><%= link_to 'Destroy', hidden_note, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hidden Note', new_hidden_note_path %>

app/views/hidden_notes/new.html.erb
<h3>New Hidden Note</h3>

<%= render 'form', hidden_note: @hidden_note %>

<!-- <%= link_to 'Back', hidden_notes_path %> -->

app/views/hidden_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Your note: </strong>
  <%= simple_format(@hidden_note.your_note) %>
</p>


<!-- <%= link_to 'Edit', edit_hidden_note_path(@hidden_note) %> | -->
<%= link_to 'New Hidden Note', new_hidden_note_url %>

app/views/hidden_notes/show_url.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>It's URL: https://do-not-keep-that.herokuapp.com/hidden_notes/<%=@hidden_note.id %></strong>

</p>

<!-- <%= link_to 'Edit', edit_hidden_note_path(@hidden_note) %> | -->
<%= link_to 'New Hidden Note', new_hidden_note_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoNotKeepThat</title>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>